### ISSUE TITLE
Allow users editing items in their inventory

### ISSUE THREAD

**Issue by nashirj** [COP4331-LargeGroupProject-Fall22/food-app#44]
~- [ ] Update quantity of item~
- [x] Delete item from inventory

**Comment by mplekunov** [comment]
Need clarification for quantity. I thought we don't quantify items. If we do, it's not a problem I just need to understand what kind of quantity it is. Is it item quantity or weight?

**Comment by nashirj** [comment]
You are right, ignore the quantity part :+1:
